### ISSUE TITLE
Support for Android S

### ISSUE THREAD

**Issue by lat233** [UsamaSarwar/twilio_voice#1]
Hi
I build the app using twill_voice for Android S and the builder says: 
"com.twilio.twilio_voice.IncomingCallNotificationService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]".

As I know, com.twilio.twilio_voice.IncomingCallNotificationService is described in the manifest file of the lib. How can I modify it to get pass this one ?
Thanks

**Comment by UsamaSarwar** [comment]
Hello,
Please update your minSdkVersion to 22+
